version: 2.1

executors:
  default:
    working_directory: ~/ci-images
    machine:

commands:
  init:
    steps:
      - run:
          name: System Update
          command: |
            sudo apt-get update -qq
            # Remove unnecessary packages for faster dist-upgrade
            sudo apt-get remove --yes \
              build-essential vim vim-runtime emacs emacs24 imagemagick \
              openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless \
              gcc gfortran-5 sbt \
              snapd ubuntu-core-launcher \
              google-chrome-stable \
              google-cloud-sdk heroku
            sudo apt-get autoremove --yes
            DEBIAN_FRONTEND=noninteractive sudo apt-get dist-upgrade --yes
      - checkout
      image: ubuntu-2004:202107-02

jobs:
  build:
    executor:
      name: default
    steps:
      - init
      - run:
          name: Test build
          command: sudo docker build --tag=phanect/ci-javascript ./ci-javascript

  release:
    executor:
      name: default
    steps:
      - init
      - run:
          name: Build Docker Image
          command: sudo docker build --tag=phanect/ci-javascript ./ci-javascript
      - run:
          name: Publish Docker Image
          command: |
            echo "$DOCKER_CLOUD_PASSWORD" | docker login --username="phanect" --password-stdin
            docker push phanect/ci-javascript

workflows:
  version: 2.1
  build-n-release:
    jobs:
      - build:
          filters: # Run when any branches & tags pushed
            branches:
              # build job is not required in master since the same command runs in release job
              ignore:
                - master
      - release:
          filters:
            branches:
              only:
                - master
  periodic:
    triggers:
      - schedule:
          cron: "8 22 * * 5" # At 22:08 on Friday
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - release
