version: 2.1

executors:
  default:
    working_directory: ~/ci-images
    machine: true

commands:
  init:
    steps:
      - run:
          name: System Update
          command: |
            sudo apt-get update -qq
            # Remove unnecessary packages for faster dist-upgrade
            sudo apt-get remove --yes \
              build-essential \
              default-jre openjdk-7-jre-headless \
              openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless \
              gcc gcc-4.8 gfortran-4.8 \
              google-chrome-stable \
              google-cloud-sdk \
              sbt
            sudo apt-get autoremove --yes
            DEBIAN_FRONTEND=noninteractive sudo apt-get dist-upgrade --yes
      - checkout

jobs:
  build:
    executor:
      name: default
    steps:
      - init
      - run:
          name: Test build
          command: sudo docker build --tag=phanect/ci-javascript ./ci-javascript

  release:
    executor:
      name: default
    steps:
      - init
      - run:
          name: Publish Docker Image
          command: |
            echo "$DOCKER_CLOUD_PASSWORD" | docker login --username="phanect" --password-stdin
            docker push phanect/ci-javascript

workflows:
  version: 2.1
  build-n-release:
    jobs:
      - build:
          filters: # Run when any branches & tags pushed
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - build
